#server:
#  port: 8081
#dataSource:
#  pooled: true
#  jmxExport: true
#  driverClassName: org.postgresql.Driver
#  username: admin
#  password: pass
#  dialect: org.hibernate.dialect.PostgreSQLDialect
#  url: jdbc:postgresql://localhost:5432/shop

  dataSource:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    pooled: true
    jmxExport: true
    dbCreate: update

  hibernate:
    cache:
      queries: false
      use_second_level_cache: false
      use_query_cache: false