spring:
  datasource:
    url: jdbc:h2:mem:shop
    driverClassName: org.h2.Driver
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080